#!/usr/bin/node

/*
#    _  _ _       _    _
 #  : \: (#)_ __ : :__: :
#   : .` : : '  \: '_ \ :
 #  :_:\_:_:_:_:_:_.__/_:
# 
 #    A Thimbl-API client for Node
#     http://www.thimbl.net
 #    Dmytri Kleiner <dk@telekommunisten.net>
*/

process.on("uncaughtException", function (err) {
  console.log("Uncaught exception: " + err);
  console.log(err.stack);
  throw err;
});

require.paths.push("scripts");
require.paths.push("scripts/vendor");
require.paths.push("scripts/vendor/jsdom/lib");
require.paths.push("scripts/vendor/node-htmlparser/lib");
require.paths.push("scripts/vendor/node-XMLHttpRequest");

var Thimbl = require("thimbl").Thimbl,
  jsdom  = require("jsdom"),
  window = jsdom.jsdom().createWindow();

var Nimbl = function() {
  return new Thimbl(window);
};

jsdom.jQueryify(window, 'jquery.js', function() {
  window.XMLHttpRequest = require("XMLHttpRequest").XMLHttpRequest;
  if (!module.parent) {
   /* Console */
    var Operetta = require("node-operetta/operetta").Operetta;
    var operetta = new Operetta();
    var nimbl = new Nimbl();
    operetta.banner = "Nimbl. A Thimbl-API client for Node.";
    operetta.parameters(["-P","--plan"], "Output Raw .plan file", function(user) {
      console.log(["=",user,"="].join(" "));
      nimbl.profile(user, function(plan) {
        console.log(plan);
      });
    });
    operetta.start();
  } else module.exports.Nimbl = Nimbl;
});

